// <auto-generated />
using System;
using CondoFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondoFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023211517_AddRejectionFields")]
    partial class AddRejectionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CondoFlow.Domain.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Apartment_Block_Number_Unique");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockId = 1,
                            Floor = 1,
                            IsActive = true,
                            Number = "101"
                        },
                        new
                        {
                            Id = 2,
                            BlockId = 1,
                            Floor = 1,
                            IsActive = true,
                            Number = "102"
                        },
                        new
                        {
                            Id = 3,
                            BlockId = 1,
                            Floor = 2,
                            IsActive = true,
                            Number = "201"
                        },
                        new
                        {
                            Id = 4,
                            BlockId = 1,
                            Floor = 2,
                            IsActive = true,
                            Number = "202"
                        },
                        new
                        {
                            Id = 5,
                            BlockId = 1,
                            Floor = 3,
                            IsActive = true,
                            Number = "301"
                        },
                        new
                        {
                            Id = 6,
                            BlockId = 1,
                            Floor = 3,
                            IsActive = true,
                            Number = "302"
                        },
                        new
                        {
                            Id = 7,
                            BlockId = 1,
                            Floor = 4,
                            IsActive = true,
                            Number = "401"
                        },
                        new
                        {
                            Id = 8,
                            BlockId = 1,
                            Floor = 4,
                            IsActive = true,
                            Number = "402"
                        },
                        new
                        {
                            Id = 9,
                            BlockId = 2,
                            Floor = 1,
                            IsActive = true,
                            Number = "101"
                        },
                        new
                        {
                            Id = 10,
                            BlockId = 2,
                            Floor = 1,
                            IsActive = true,
                            Number = "102"
                        },
                        new
                        {
                            Id = 11,
                            BlockId = 2,
                            Floor = 2,
                            IsActive = true,
                            Number = "201"
                        },
                        new
                        {
                            Id = 12,
                            BlockId = 2,
                            Floor = 2,
                            IsActive = true,
                            Number = "202"
                        },
                        new
                        {
                            Id = 13,
                            BlockId = 2,
                            Floor = 3,
                            IsActive = true,
                            Number = "301"
                        },
                        new
                        {
                            Id = 14,
                            BlockId = 2,
                            Floor = 3,
                            IsActive = true,
                            Number = "302"
                        },
                        new
                        {
                            Id = 15,
                            BlockId = 2,
                            Floor = 4,
                            IsActive = true,
                            Number = "401"
                        },
                        new
                        {
                            Id = 16,
                            BlockId = 2,
                            Floor = 4,
                            IsActive = true,
                            Number = "402"
                        },
                        new
                        {
                            Id = 17,
                            BlockId = 2,
                            Floor = 5,
                            IsActive = true,
                            Number = "501"
                        },
                        new
                        {
                            Id = 18,
                            BlockId = 3,
                            Floor = 1,
                            IsActive = true,
                            Number = "101"
                        },
                        new
                        {
                            Id = 19,
                            BlockId = 3,
                            Floor = 2,
                            IsActive = true,
                            Number = "201"
                        },
                        new
                        {
                            Id = 20,
                            BlockId = 3,
                            Floor = 3,
                            IsActive = true,
                            Number = "301"
                        },
                        new
                        {
                            Id = 21,
                            BlockId = 3,
                            Floor = 4,
                            IsActive = true,
                            Number = "401"
                        },
                        new
                        {
                            Id = 22,
                            BlockId = 4,
                            Floor = 1,
                            IsActive = true,
                            Number = "101"
                        },
                        new
                        {
                            Id = 23,
                            BlockId = 4,
                            Floor = 1,
                            IsActive = true,
                            Number = "102"
                        },
                        new
                        {
                            Id = 24,
                            BlockId = 4,
                            Floor = 2,
                            IsActive = true,
                            Number = "201"
                        },
                        new
                        {
                            Id = 25,
                            BlockId = 4,
                            Floor = 2,
                            IsActive = true,
                            Number = "202"
                        },
                        new
                        {
                            Id = 26,
                            BlockId = 4,
                            Floor = 3,
                            IsActive = true,
                            Number = "301"
                        },
                        new
                        {
                            Id = 27,
                            BlockId = 4,
                            Floor = 3,
                            IsActive = true,
                            Number = "302"
                        },
                        new
                        {
                            Id = 28,
                            BlockId = 4,
                            Floor = 4,
                            IsActive = true,
                            Number = "401"
                        },
                        new
                        {
                            Id = 29,
                            BlockId = 4,
                            Floor = 4,
                            IsActive = true,
                            Number = "402"
                        },
                        new
                        {
                            Id = 30,
                            BlockId = 5,
                            Floor = 1,
                            IsActive = true,
                            Number = "101"
                        },
                        new
                        {
                            Id = 31,
                            BlockId = 5,
                            Floor = 1,
                            IsActive = true,
                            Number = "102"
                        },
                        new
                        {
                            Id = 32,
                            BlockId = 5,
                            Floor = 2,
                            IsActive = true,
                            Number = "201"
                        },
                        new
                        {
                            Id = 33,
                            BlockId = 5,
                            Floor = 2,
                            IsActive = true,
                            Number = "202"
                        },
                        new
                        {
                            Id = 34,
                            BlockId = 5,
                            Floor = 3,
                            IsActive = true,
                            Number = "301"
                        },
                        new
                        {
                            Id = 35,
                            BlockId = 5,
                            Floor = 3,
                            IsActive = true,
                            Number = "302"
                        },
                        new
                        {
                            Id = 36,
                            BlockId = 5,
                            Floor = 4,
                            IsActive = true,
                            Number = "401"
                        },
                        new
                        {
                            Id = 37,
                            BlockId = 5,
                            Floor = 4,
                            IsActive = true,
                            Number = "402"
                        },
                        new
                        {
                            Id = 38,
                            BlockId = 5,
                            Floor = 5,
                            IsActive = true,
                            Number = "501"
                        });
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bloque Q",
                            IsActive = true,
                            Name = "Q"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bloque P",
                            IsActive = true,
                            Name = "P"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bloque N",
                            IsActive = true,
                            Name = "N"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bloque M",
                            IsActive = true,
                            Name = "M"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bloque O",
                            IsActive = true,
                            Name = "O"
                        });
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Debts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87654321-4321-4321-4321-210987654321"),
                            Concept = "Mantenimiento Diciembre 2024",
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 12,
                            OwnerId = new Guid("12345678-1234-1234-1234-123456789012"),
                            Status = "Pending",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CondoFlow.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUser_ApartmentId_Unique")
                        .HasFilter("[ApartmentId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Apartment", b =>
                {
                    b.HasOne("CondoFlow.Domain.Entities.Block", "Block")
                        .WithMany("Apartments")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Debt", b =>
                {
                    b.OwnsOne("CondoFlow.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("DebtId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("DebtId");

                            b1.ToTable("Debts");

                            b1.WithOwner()
                                .HasForeignKey("DebtId");

                            b1.HasData(
                                new
                                {
                                    DebtId = new Guid("87654321-4321-4321-4321-210987654321"),
                                    Amount = 1800.00m,
                                    Currency = "DOP"
                                });
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Payment", b =>
                {
                    b.HasOne("CondoFlow.Domain.Entities.Debt", "Debt")
                        .WithMany()
                        .HasForeignKey("DebtId");

                    b.OwnsOne("CondoFlow.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Debt");
                });

            modelBuilder.Entity("CondoFlow.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("CondoFlow.Domain.Entities.Apartment", "ApartmentEntity")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApartmentEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CondoFlow.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CondoFlow.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CondoFlow.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CondoFlow.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CondoFlow.Domain.Entities.Block", b =>
                {
                    b.Navigation("Apartments");
                });
#pragma warning restore 612, 618
        }
    }
}
